import type { IndexToken } from "@/types";

// Top ~60 crypto tokens that are always relevant — available instantly without any network call.
// Supplemented at runtime by Birdeye (Solana trending) and CoinGecko (market cap).
export const CRYPTO_FALLBACK: IndexToken[] = [
  { ticker: "BTC",   name: "Bitcoin",              type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "ETH",   name: "Ethereum",             type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "SOL",   name: "Solana",               type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "BNB",   name: "BNB",                  type: "crypto", chain: "BSC",  address: null, exchange: null },
  { ticker: "XRP",   name: "XRP",                  type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "TON",   name: "Toncoin",              type: "crypto", chain: "TON",  address: null, exchange: null },
  { ticker: "AVAX",  name: "Avalanche",            type: "crypto", chain: "AVAX", address: null, exchange: null },
  { ticker: "DOGE",  name: "Dogecoin",             type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "SHIB",  name: "Shiba Inu",            type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "LINK",  name: "Chainlink",            type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "DOT",   name: "Polkadot",             type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "ADA",   name: "Cardano",              type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "LTC",   name: "Litecoin",             type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "BCH",   name: "Bitcoin Cash",         type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "UNI",   name: "Uniswap",              type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "POL",   name: "Polygon",              type: "crypto", chain: "POL",  address: null, exchange: null },
  { ticker: "MATIC", name: "Polygon (MATIC)",      type: "crypto", chain: "POL",  address: null, exchange: null },
  { ticker: "ARB",   name: "Arbitrum",             type: "crypto", chain: "ARB",  address: null, exchange: null },
  { ticker: "OP",    name: "Optimism",             type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "SUI",   name: "Sui",                  type: "crypto", chain: "SUI",  address: null, exchange: null },
  { ticker: "APT",   name: "Aptos",                type: "crypto", chain: "APT",  address: null, exchange: null },
  { ticker: "NEAR",  name: "NEAR Protocol",        type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "ATOM",  name: "Cosmos",               type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "ICP",   name: "Internet Computer",    type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "FIL",   name: "Filecoin",             type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "HBAR",  name: "Hedera",               type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "FTM",   name: "Fantom",               type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "AAVE",  name: "Aave",                 type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "MKR",   name: "Maker",                type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "CRV",   name: "Curve DAO Token",      type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "GMX",   name: "GMX",                  type: "crypto", chain: "ARB",  address: null, exchange: null },
  { ticker: "LDO",   name: "Lido DAO",             type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "ONDO",  name: "Ondo Finance",         type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "TAO",   name: "Bittensor",            type: "crypto", chain: null,   address: null, exchange: null },
  { ticker: "DYDX",  name: "dYdX",                 type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "ENS",   name: "Ethereum Name Service",type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "IMX",   name: "Immutable X",          type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "PEPE",  name: "Pepe",                 type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "BONK",  name: "Bonk",                 type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "WIF",   name: "dogwifhat",            type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "POPCAT",name: "Popcat",               type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "TRUMP", name: "Official Trump",       type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "FART",  name: "Fartcoin",             type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "PENGU", name: "Pudgy Penguins",       type: "crypto", chain: "SOL",  address: null, exchange: null },
  { ticker: "WBTC",  name: "Wrapped Bitcoin",      type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "WETH",  name: "Wrapped Ether",        type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "STETH", name: "Lido Staked Ether",   type: "crypto", chain: "ETH",  address: null, exchange: null },
  // Multi-chain stablecoins — explicit SOL + ETH entries with known addresses.
  // The live Birdeye SOL tokenlist often omits these, so we hardcode them to
  // ensure SOL users always get the correct chain and contract address.
  { ticker: "USDC",  name: "USD Coin",             type: "crypto", chain: "SOL",  address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", exchange: null },
  { ticker: "USDC",  name: "USD Coin",             type: "crypto", chain: "ETH",  address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", exchange: null },
  { ticker: "USDT",  name: "Tether",               type: "crypto", chain: "SOL",  address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB", exchange: null },
  { ticker: "USDT",  name: "Tether",               type: "crypto", chain: "ETH",  address: "0xdAC17F958D2ee523a2206206994597C13D831ec7", exchange: null },
  { ticker: "DAI",   name: "Dai",                  type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "MANA",  name: "Decentraland",         type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "SAND",  name: "The Sandbox",          type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "AXS",   name: "Axie Infinity",        type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "DEGEN", name: "Degen",                type: "crypto", chain: "BASE", address: null, exchange: null },
  { ticker: "BRETT", name: "Brett",                type: "crypto", chain: "BASE", address: null, exchange: null },
  { ticker: "VIRTUAL",name: "Virtuals Protocol",   type: "crypto", chain: "BASE", address: null, exchange: null },
  { ticker: "HYPE",  name: "Hyperliquid",          type: "crypto", chain: "ETH",  address: null, exchange: null },
  { ticker: "MOG",   name: "Mog Coin",             type: "crypto", chain: "ETH",  address: null, exchange: null },
];
