import type { IndexToken } from "@/types";

// Top ~130 US stocks by tweet frequency / market relevance
// Covers virtually every stock discussed on financial Twitter
const STOCKS: Array<[string, string, "NASDAQ" | "NYSE" | "NYSEARCA" | "CBOE"]> = [
  // Market indexes (CBOE) — commonly used as cashtags
  ["SPX",   "S&P 500 Index",                "CBOE"],
  ["NDX",   "Nasdaq 100 Index",             "CBOE"],
  ["RUT",   "Russell 2000 Index",           "CBOE"],
  ["VIX",   "CBOE Volatility Index",        "CBOE"],
  ["SPY",   "SPDR S&P 500 ETF",            "NYSEARCA"],
  // Mega-cap tech
  ["AAPL",  "Apple Inc.",                   "NASDAQ"],
  ["MSFT",  "Microsoft Corp.",              "NASDAQ"],
  ["NVDA",  "NVIDIA Corp.",                 "NASDAQ"],
  ["GOOGL", "Alphabet Inc.",                "NASDAQ"],
  ["GOOG",  "Alphabet Inc. Class C",        "NASDAQ"],
  ["AMZN",  "Amazon.com Inc.",              "NASDAQ"],
  ["META",  "Meta Platforms Inc.",          "NASDAQ"],
  ["TSLA",  "Tesla Inc.",                   "NASDAQ"],
  ["NFLX",  "Netflix Inc.",                 "NASDAQ"],
  ["ORCL",  "Oracle Corp.",                 "NYSE"],
  ["CRM",   "Salesforce Inc.",              "NYSE"],
  ["ADBE",  "Adobe Inc.",                   "NASDAQ"],
  ["NOW",   "ServiceNow Inc.",              "NYSE"],
  ["UBER",  "Uber Technologies Inc.",       "NYSE"],
  ["LYFT",  "Lyft Inc.",                    "NASDAQ"],
  ["SNAP",  "Snap Inc.",                    "NYSE"],
  ["PINS",  "Pinterest Inc.",               "NYSE"],
  ["RDDT",  "Reddit Inc.",                  "NYSE"],
  ["SHOP",  "Shopify Inc.",                 "NYSE"],
  ["PLTR",  "Palantir Technologies",        "NYSE"],
  ["RBLX",  "Roblox Corp.",                 "NYSE"],
  ["ROKU",  "Roku Inc.",                    "NASDAQ"],
  ["ZM",    "Zoom Video Communications",   "NASDAQ"],
  ["DOCU",  "DocuSign Inc.",                "NASDAQ"],
  ["TWLO",  "Twilio Inc.",                  "NYSE"],
  ["SOFI",  "SoFi Technologies Inc.",       "NASDAQ"],
  // Semiconductors
  ["AMD",   "Advanced Micro Devices",       "NASDAQ"],
  ["INTC",  "Intel Corp.",                  "NASDAQ"],
  ["QCOM",  "Qualcomm Inc.",                "NASDAQ"],
  ["ARM",   "Arm Holdings plc",             "NASDAQ"],
  ["TSM",   "Taiwan Semiconductor",         "NYSE"],
  ["ASML",  "ASML Holding NV",             "NASDAQ"],
  ["AVGO",  "Broadcom Inc.",                "NASDAQ"],
  ["MU",    "Micron Technology",            "NASDAQ"],
  ["AMAT",  "Applied Materials Inc.",       "NASDAQ"],
  ["KLAC",  "KLA Corp.",                    "NASDAQ"],
  ["LRCX",  "Lam Research Corp.",           "NASDAQ"],
  ["MRVL",  "Marvell Technology Inc.",      "NASDAQ"],
  ["TXN",   "Texas Instruments Inc.",       "NASDAQ"],
  ["SMCI",  "Super Micro Computer",         "NASDAQ"],
  ["MCHP",  "Microchip Technology",         "NASDAQ"],
  ["ON",    "ON Semiconductor Corp.",       "NASDAQ"],
  // Finance
  ["JPM",   "JPMorgan Chase & Co.",         "NYSE"],
  ["BAC",   "Bank of America Corp.",        "NYSE"],
  ["GS",    "Goldman Sachs Group",          "NYSE"],
  ["MS",    "Morgan Stanley",               "NYSE"],
  ["C",     "Citigroup Inc.",               "NYSE"],
  ["WFC",   "Wells Fargo & Co.",            "NYSE"],
  ["BLK",   "BlackRock Inc.",               "NYSE"],
  ["SCHW",  "Charles Schwab Corp.",         "NYSE"],
  ["AXP",   "American Express Co.",         "NYSE"],
  ["V",     "Visa Inc.",                    "NYSE"],
  ["MA",    "Mastercard Inc.",              "NYSE"],
  ["PYPL",  "PayPal Holdings Inc.",         "NASDAQ"],
  ["HOOD",  "Robinhood Markets Inc.",       "NASDAQ"],
  // Crypto-adjacent
  ["COIN",  "Coinbase Global Inc.",         "NASDAQ"],
  ["MSTR",  "MicroStrategy Inc.",           "NASDAQ"],
  ["MARA",  "MARA Holdings Inc.",           "NASDAQ"],
  ["RIOT",  "Riot Platforms Inc.",          "NASDAQ"],
  ["HUT",   "Hut 8 Corp.",                  "NASDAQ"],
  ["CLSK",  "CleanSpark Inc.",              "NASDAQ"],
  ["BTBT",  "Bit Brother Ltd.",             "NASDAQ"],
  ["CIFR",  "Cipher Mining Inc.",           "NASDAQ"],
  // Healthcare / Pharma
  ["JNJ",   "Johnson & Johnson",            "NYSE"],
  ["PFE",   "Pfizer Inc.",                  "NYSE"],
  ["MRNA",  "Moderna Inc.",                 "NASDAQ"],
  ["LLY",   "Eli Lilly and Co.",            "NYSE"],
  ["ABBV",  "AbbVie Inc.",                  "NYSE"],
  ["AMGN",  "Amgen Inc.",                   "NASDAQ"],
  ["GILD",  "Gilead Sciences Inc.",         "NASDAQ"],
  ["VRTX",  "Vertex Pharmaceuticals",       "NASDAQ"],
  ["REGN",  "Regeneron Pharmaceuticals",    "NASDAQ"],
  ["ISRG",  "Intuitive Surgical Inc.",      "NASDAQ"],
  // Energy
  ["XOM",   "Exxon Mobil Corp.",            "NYSE"],
  ["CVX",   "Chevron Corp.",                "NYSE"],
  ["ENPH",  "Enphase Energy Inc.",          "NASDAQ"],
  ["FSLR",  "First Solar Inc.",             "NASDAQ"],
  ["NEE",   "NextEra Energy Inc.",          "NYSE"],
  ["OXY",   "Occidental Petroleum",         "NYSE"],
  ["SLB",   "Schlumberger Ltd.",            "NYSE"],
  // Consumer / Retail
  ["WMT",   "Walmart Inc.",                 "NYSE"],
  ["TGT",   "Target Corp.",                 "NYSE"],
  ["COST",  "Costco Wholesale Corp.",       "NASDAQ"],
  ["HD",    "Home Depot Inc.",              "NYSE"],
  ["LOW",   "Lowe's Companies Inc.",        "NYSE"],
  ["NKE",   "Nike Inc.",                    "NYSE"],
  ["SBUX",  "Starbucks Corp.",              "NASDAQ"],
  ["MCD",   "McDonald's Corp.",             "NYSE"],
  ["KO",    "Coca-Cola Co.",                "NYSE"],
  ["PEP",   "PepsiCo Inc.",                 "NASDAQ"],
  ["DIS",   "Walt Disney Co.",              "NYSE"],
  ["LULU",  "Lululemon Athletica",          "NASDAQ"],
  ["ELF",   "e.l.f. Beauty Inc.",           "NYSE"],
  // Autos
  ["F",     "Ford Motor Co.",               "NYSE"],
  ["GM",    "General Motors Co.",           "NYSE"],
  ["RIVN",  "Rivian Automotive Inc.",       "NASDAQ"],
  ["LCID",  "Lucid Group Inc.",             "NASDAQ"],
  ["RACE",  "Ferrari NV",                   "NYSE"],
  ["STLA",  "Stellantis NV",               "NYSE"],
  // Airlines
  ["UAL",   "United Airlines Holdings",     "NASDAQ"],
  ["DAL",   "Delta Air Lines Inc.",         "NYSE"],
  ["AAL",   "American Airlines Group",      "NASDAQ"],
  ["LUV",   "Southwest Airlines Co.",       "NYSE"],
  ["JBLU",  "JetBlue Airways Corp.",        "NASDAQ"],
  // Meme / high-retail
  ["GME",   "GameStop Corp.",               "NYSE"],
  ["AMC",   "AMC Entertainment Holdings",  "NYSE"],
  ["BB",    "BlackBerry Ltd.",              "NYSE"],
  ["SPCE",  "Virgin Galactic Holdings",     "NYSE"],
  // China ADRs
  ["BABA",  "Alibaba Group Holding",        "NYSE"],
  ["JD",    "JD.com Inc.",                  "NASDAQ"],
  ["NIO",   "NIO Inc.",                     "NYSE"],
  ["XPEV",  "XPeng Inc.",                   "NYSE"],
  ["LI",    "Li Auto Inc.",                 "NASDAQ"],
  // ETFs
  ["QQQ",   "Invesco QQQ Trust",            "NASDAQ"],
  ["IWM",   "iShares Russell 2000 ETF",    "NYSEARCA"],
  ["DIA",   "SPDR Dow Jones ETF",          "NYSEARCA"],
  ["VTI",   "Vanguard Total Stock ETF",    "NYSEARCA"],
  ["VOO",   "Vanguard S&P 500 ETF",        "NYSEARCA"],
  ["VXX",   "iPath Series B VIX ETN",      "NYSEARCA"],
  ["TQQQ",  "ProShares UltraPro QQQ",      "NASDAQ"],
  ["SQQQ",  "ProShares UltraPro Short QQQ","NASDAQ"],
  ["SOXL",  "Direxion Daily Semis Bull 3X","NYSEARCA"],
  ["SOXS",  "Direxion Daily Semis Bear 3X","NYSEARCA"],
  ["ARKK",  "ARK Innovation ETF",          "NYSEARCA"],
  ["GLD",   "SPDR Gold Shares",            "NYSEARCA"],
  ["SLV",   "iShares Silver Trust",        "NYSEARCA"],
  ["USO",   "United States Oil Fund",      "NYSEARCA"],
  ["TLT",   "iShares 20+ Year Treasury ETF","NASDAQ"],
  ["UVXY",  "ProShares Ultra VIX ETF",     "NYSEARCA"],
];

export const STOCK_INDEX: IndexToken[] = STOCKS.map(([ticker, name, exchange]) => ({
  ticker,
  name,
  type: "stock" as const,
  chain: null,
  address: null,
  exchange,
}));
